### PR TITLE
Add MQTT support

### PR DESCRIPTION
**Pull request by filinvadim**
MQTT pubsub driver for Go Cloud Development Kit

REFERENCES:
https://github.com/google/go-cloud/issues/1466

https://github.com/google/go-cloud/pull/2751

### CODE REVIEW

**Comment by Kale-Grabovski** [comment]
How long does it take to review this pr?

**Comment by kpacha** [comment]
I can't give an accurate estimate because we're closing a release, but we check and appreciate  every issue and pr, so don't panic it will be review in a week or so.

**Comment by kpacha** [comment]
@filinvadim, great job! I think the pkg is promising even at its early stage (the project is not very mature). After a quick review of the code there are some things I think could be problematic, such as using infinite waits at the subscribe and publish methods or the lack of parameters

please, let us know when the project is a little more mature and we'll resume the integration process

cheers!

**Comment by filinvadim** [comment]
@kpacha this project and the whole code was copied from existing go-cloud pubsub drivers. So according your logic go-cloud immature too :)
I'll fix infinite waits at the subscribe and publish methods or the lack of parameters.

**Comment by filinvadim** [comment]
Infinite waits and lack of parameters were fixed.

**Comment by filinvadim** [comment]
@kpacha sorry for bothering you by my employer keeps poking me about this pr

**Comment by alombarte** [comment]
@filinvadim we offer professional services and consultancy for Enterprises. This repository is open-source. Get in touch: support AT devops DOT faith.

**Comment by filinvadim** [comment]
Guys?

**Comment by alombarte** [comment]
Hello @filinvadim 

Thanks for the time you spent on this new functionality. Although we don't have a market for this kind of feature currently, I was initially excited to see MQTT support, and I asked the team to go through this PR. 

We take very seriously all the components and functionalities that are added in the gateway as they impact a broad base of users. Some of the things we evaluate internally are performance, long-term support, licensing, production usage of included libraries, etc.

The krakend pubsub component is included in all our KrakenD Enterprise offerings. It's a cornerstone for service connectivity and needs much more attention from our side than other pieces of the gateway as the impact of adding code is more prominent.
The first thing that refrains me for accepting the PR is that the library our project will depend on, cannot be considered to be yet in production. It seems that there is no usage or references to the library, only 1 contributor, and not backed (hosted) by a company:
https://pkg.go.dev/github.com/filinvadim/go-cloud-pubsub-mqtt?tab=importedby

The library has only 5 commits.

When going through the implementation, we've found other problems related to performance and configuration. I do not put in doubt the value of the contribution, and I am sure this solution will work for you, but I am not confident of adding it to all our user base. 

My recommendation would be referencing your own component in your main.go (and will be your first imported of the library :wink:). For now we won't merge the feature. We can review it again  when there is official support of Google Cloud to the MQTT functionality.

Спасибо

**Pull request closed without merging**
